# Generated by Django 5.2.6 on 2026-09-10 22:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('PROVEEDOR', 'Proveedor'), ('PRESTAMO', 'Préstamo'), ('OTRO', 'Otra deuda')], db_index=True, default='OTRO', max_length=10)),
                ('concepto', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['tipo'], name='balance_deu_tipo_e75903_idx'), models.Index(fields=['fecha'], name='balance_deu_fecha_766b7c_idx'), models.Index(fields=['fecha_vencimiento'], name='balance_deu_fecha_v_9b770d_idx')],
            },
        ),
        migrations.CreateModel(
            name='OtroDinero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('BANCO', 'Banco'), ('OTRO', 'Otro')], db_index=True, default='OTRO', max_length=10)),
                ('concepto', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['tipo'], name='balance_otr_tipo_97bb2a_idx'), models.Index(fields=['fecha'], name='balance_otr_fecha_e105f4_idx')],
            },
        ),
    ]
