# Generated by Django 5.2.6 on 2026-09-10 21:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PEDIDO', 'Pedido'), ('OTRA', 'Otra cartera')], db_index=True, default='PEDIDO', max_length=10)),
                ('nombre', models.CharField(max_length=150)),
                ('concepto', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada')], db_index=True, default='PENDIENTE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pedido', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cartera', to='orders.pedido')),
            ],
            options={
                'ordering': ['-fecha_inicio', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha', models.DateField()),
                ('concepto', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cartera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='cartera.cartera')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='cartera',
            index=models.Index(fields=['tipo'], name='cartera_car_tipo_a8b227_idx'),
        ),
        migrations.AddIndex(
            model_name='cartera',
            index=models.Index(fields=['estado'], name='cartera_car_estado_6feb36_idx'),
        ),
        migrations.AddIndex(
            model_name='cartera',
            index=models.Index(fields=['fecha_inicio'], name='cartera_car_fecha_i_31ec54_idx'),
        ),
        migrations.AddIndex(
            model_name='cartera',
            index=models.Index(fields=['fecha_vencimiento'], name='cartera_car_fecha_v_287768_idx'),
        ),
        migrations.AddIndex(
            model_name='abono',
            index=models.Index(fields=['cartera'], name='cartera_abo_cartera_8f7ca5_idx'),
        ),
        migrations.AddIndex(
            model_name='abono',
            index=models.Index(fields=['fecha'], name='cartera_abo_fecha_ba9b26_idx'),
        ),
    ]
