# Generated by Django 5.2.6 on 2026-09-09 19:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=150, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('clasificacion', models.CharField(choices=[('CAMISAS', 'Camisas'), ('PANTALONES', 'Pantalones'), ('CALZADO', 'Calzado'), ('ACCESORIOS', 'Accesorios'), ('ELECTRONICA', 'Electrónica'), ('HOGAR', 'Hogar'), ('OFICINA', 'Oficina'), ('ALIMENTOS', 'Alimentos'), ('BEBIDAS', 'Bebidas'), ('OTROS', 'Otros')], max_length=30)),
                ('unidad_medida', models.CharField(choices=[('UNIDAD', 'Unidad'), ('CAJA', 'Caja'), ('PAQUETE', 'Paquete'), ('DOCENA', 'Docena'), ('KILOGRAMO', 'Kilogramo'), ('GRAMO', 'Gramo'), ('LITRO', 'Litro'), ('MILILITRO', 'Mililitro'), ('METRO', 'Metro')], max_length=20)),
                ('costo_base', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('alerta_minimo', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('ubicacion_almacen', models.CharField(blank=True, max_length=150)),
                ('color', models.CharField(blank=True, max_length=80)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], db_index=True, default='ACTIVO', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['descripcion', 'id'],
                'indexes': [models.Index(fields=['estado'], name='inventory_a_estado_836758_idx'), models.Index(fields=['clasificacion'], name='inventory_a_clasifi_88ca08_idx')],
            },
        ),
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('ubicacion', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_inventario', to='inventory.articulo')),
            ],
            options={
                'ordering': ['articulo__descripcion', 'id'],
                'indexes': [models.Index(fields=['articulo'], name='inventory_i_articul_ffdeb4_idx')],
            },
        ),
    ]
