# Generated by Django 5.2.6 on 2026-09-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='clasificacion',
            field=models.CharField(choices=[('CAMISAS', 'Camisas'), ('PANTALONES', 'Pantalones'), ('CALZADO', 'Calzado'), ('ACCESORIOS', 'Accesorios'), ('ELECTRONICA', 'Electrónica'), ('HOGAR', 'Hogar'), ('OFICINA', 'Oficina'), ('ALIMENTOS', 'Alimentos'), ('BEBIDAS', 'Bebidas'), ('OTROS', 'Otros'), ('NACIONAL', 'Nacional')], max_length=30),
        ),
    ]
